[build]
publish = "dist/"
command = "yarn build"

[build.environment]
# Build Previews
NODE_ENV = "production"
YARN_FLAGS = "--production=false"

[context.production.environment]

# Redirect rule for compatibility with Vue Router
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
